# Generated by Django 5.1.6 on 2025-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_preset_alter_ink_extra_charges_alter_ink_freight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperreel',
            name='bf',
        ),
        migrations.RemoveField(
            model_name='paperreel',
            name='extra_charges',
        ),
        migrations.RemoveField(
            model_name='paperreel',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='paperreel',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='paperreel',
            name='total_price_ex_tax',
        ),
        migrations.RemoveField(
            model_name='pastinggum',
            name='extra_charges',
        ),
        migrations.RemoveField(
            model_name='pastinggum',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='pastinggum',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='pastinggum',
            name='total_price_ex_tax',
        ),
        migrations.RemoveField(
            model_name='pastinggum',
            name='weight_per_bag',
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='preset',
            name='category',
            field=models.CharField(choices=[('gsm', 'GSM'), ('company', 'Company Name'), ('gum_type', 'Gum Type'), ('color', 'Ink Color'), ('roll_type', 'Strapping Roll Type'), ('coil_type', 'Pin Coil Type')], max_length=50),
        ),
    ]
