# Generated by Django 5.1.6 on 2025-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_ink_company_name_alter_ink_extra_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('item_id', models.IntegerField()),
                ('action', models.CharField(choices=[('ADD', 'Added'), ('EDIT', 'Modified'), ('DELETE', 'Deleted')], max_length=10)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default='System', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
