# Generated by Django 5.1.6 on 2025-03-09 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('flute_type', models.CharField(choices=[('A', 'A Flute'), ('B', 'B Flute'), ('C', 'C Flute')], max_length=1)),
                ('number_of_plies', models.IntegerField(choices=[(3, '3 Ply'), (5, '5 Ply'), (7, '7 Ply')])),
                ('print_color', models.CharField(max_length=50)),
                ('boxes_ordered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='boxproductionrequirements',
            name='box',
        ),
        migrations.DeleteModel(
            name='BoxDetails',
        ),
        migrations.DeleteModel(
            name='BoxProductionRequirements',
        ),
    ]
