# Generated by Django 5.1.6 on 2025-03-09 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0002_boxspecification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('flute_type', models.CharField(choices=[('A', 'A Flute'), ('B', 'B Flute'), ('C', 'C Flute')], max_length=1)),
                ('num_plies', models.IntegerField(choices=[(3, '3 Ply'), (5, '5 Ply'), (7, '7 Ply')])),
                ('print_color', models.CharField(max_length=50)),
                ('order_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['box_name'], name='finished_go_box_nam_dd71c5_idx'), models.Index(fields=['flute_type'], name='finished_go_flute_t_1de36f_idx'), models.Index(fields=['print_color'], name='finished_go_print_c_4d1625_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoxProductionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_paper_gsm', models.IntegerField()),
                ('top_paper_bf', models.IntegerField()),
                ('flute_paper_gsm', models.IntegerField(blank=True, null=True)),
                ('flute_paper_bf', models.IntegerField(blank=True, null=True)),
                ('middle_paper_gsm', models.IntegerField(blank=True, null=True)),
                ('middle_paper_bf', models.IntegerField(blank=True, null=True)),
                ('bottom_paper_gsm', models.IntegerField()),
                ('bottom_paper_bf', models.IntegerField()),
                ('box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finished_goods.boxdetails')),
            ],
        ),
    ]
