# Generated by Django 5.1.7 on 2025-03-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0005_boxtemplate_boxorder_manufacturingcost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxorder',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='boxorder',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='box_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finished_goods.boxdetails'),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='boxorder',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Order Placed'), ('MANUFACTURING', 'Manufacturing'), ('PRODUCTION_COMPLETE', 'Production Complete'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='PLACED', max_length=20),
        ),
    ]
