# Generated by Django 5.1.6 on 2025-02-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('breadth', models.FloatField()),
                ('height', models.FloatField()),
                ('flute_type', models.CharField(max_length=50)),
                ('num_plies', models.IntegerField()),
                ('print_color', models.CharField(max_length=50)),
                ('order_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoxProductionRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_paper_gsm', models.IntegerField()),
                ('flute_paper_gsm', models.IntegerField(blank=True, null=True)),
                ('middle_paper_gsm', models.IntegerField(blank=True, null=True)),
                ('bottom_paper_gsm', models.IntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finished_goods.boxdetails')),
            ],
        ),
    ]
