# Generated by Django 5.1.6 on 2025-03-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0003_boxdetails_boxproductionrequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPaperRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_paper_gsm', models.IntegerField()),
                ('top_paper_bf', models.IntegerField()),
                ('bottom_paper_gsm', models.IntegerField()),
                ('bottom_paper_bf', models.IntegerField()),
                ('flute_paper_gsm', models.IntegerField(blank=True, null=True)),
                ('flute_paper_bf', models.IntegerField(blank=True, null=True)),
                ('flute_paper1_gsm', models.IntegerField(blank=True, null=True)),
                ('flute_paper1_bf', models.IntegerField(blank=True, null=True)),
                ('middle_paper_gsm', models.IntegerField(blank=True, null=True)),
                ('middle_paper_bf', models.IntegerField(blank=True, null=True)),
                ('flute_paper2_gsm', models.IntegerField(blank=True, null=True)),
                ('flute_paper2_bf', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boxproductionrequirements',
            name='box',
        ),
        migrations.RemoveIndex(
            model_name='boxdetails',
            name='finished_go_box_nam_dd71c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='boxdetails',
            name='finished_go_flute_t_1de36f_idx',
        ),
        migrations.RemoveIndex(
            model_name='boxdetails',
            name='finished_go_print_c_4d1625_idx',
        ),
        migrations.RemoveField(
            model_name='boxdetails',
            name='notes',
        ),
        migrations.AddField(
            model_name='boxdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boxdetails',
            name='box_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='boxpaperrequirements',
            name='box',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finished_goods.boxdetails'),
        ),
        migrations.DeleteModel(
            name='BoxProductionRequirements',
        ),
    ]
