# Generated by Django 5.1.6 on 2025-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('weight_per_can', models.FloatField(default=0.0)),
                ('company_name', models.CharField(max_length=100)),
                ('total_qty', models.IntegerField(default=0)),
                ('price_per_kg', models.FloatField(default=0.0)),
                ('freight', models.FloatField(default=0.0)),
                ('extra_charges', models.FloatField(default=0.0)),
                ('total_price_ex_tax', models.FloatField(default=0.0)),
                ('tax_percent', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinCoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_type', models.CharField(max_length=50)),
                ('total_qty', models.IntegerField()),
                ('price_per_kg', models.FloatField()),
                ('freight', models.FloatField()),
                ('extra_charges', models.FloatField()),
                ('total_price_ex_tax', models.FloatField()),
                ('tax_percent', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrappingRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(max_length=50)),
                ('meters_per_roll', models.FloatField()),
                ('weight_per_roll', models.FloatField()),
                ('total_qty', models.IntegerField()),
                ('price_per_kg', models.FloatField()),
                ('freight', models.FloatField()),
                ('extra_charges', models.FloatField()),
                ('total_price_ex_tax', models.FloatField()),
                ('tax_percent', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='paperreel',
            name='bf',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='paperreel',
            name='extra_charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paperreel',
            name='freight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paperreel',
            name='tax_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paperreel',
            name='total_price_ex_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pastinggum',
            name='extra_charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pastinggum',
            name='freight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pastinggum',
            name='tax_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pastinggum',
            name='total_price_ex_tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pastinggum',
            name='weight_per_bag',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='price_per_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
