# Generated by Django 5.1.6 on 2025-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ink_pincoil_strappingroll_paperreel_bf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gsm', 'GSM'), ('company', 'Company Name'), ('gum_type', 'Gum Type')], max_length=50)),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ink',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ink',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ink',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ink',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ink',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ink',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ink',
            name='weight_per_can',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorysummary',
            name='gsm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorysummary',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='bf',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='gsm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='weight_per_bag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='meters_per_roll',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='weight_per_roll',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
