# Generated by Django 5.1.6 on 2025-02-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_paperreel_bf_alter_ink_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ink',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='bf',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='coil_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='roll_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
