# Generated by Django 5.1.6 on 2025-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_ink_company_name_alter_paperreel_bf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ink',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ink',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ink',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ink',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ink',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ink',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ink',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ink',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ink',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ink',
            name='weight_per_can',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='bf',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paperreel',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pastinggum',
            name='weight_per_bag',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='coil_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pincoil',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='meters_per_roll',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='roll_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='total_price_ex_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='total_qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='strappingroll',
            name='weight_per_roll',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
