# Generated by Django 5.1.6 on 2025-03-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('weight_per_can', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cans', models.PositiveIntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_alert', models.PositiveIntegerField(default=5)),
                ('max_stock_alert', models.PositiveIntegerField(default=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ink Summaries',
                'unique_together': {('color', 'weight_per_can')},
            },
        ),
        migrations.CreateModel(
            name='PaperReelSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm', models.PositiveIntegerField()),
                ('bf', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_rolls', models.PositiveIntegerField(default=0)),
                ('avg_price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_alert', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('max_stock_alert', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Paper Reel Summaries',
                'unique_together': {('gsm', 'bf', 'size')},
            },
        ),
        migrations.CreateModel(
            name='PastingGumSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gum_type', models.CharField(max_length=100)),
                ('weight_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bags', models.PositiveIntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_alert', models.PositiveIntegerField(default=10)),
                ('max_stock_alert', models.PositiveIntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pasting Gum Summaries',
                'unique_together': {('gum_type', 'weight_per_bag')},
            },
        ),
        migrations.CreateModel(
            name='PinCoilSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_type', models.CharField(max_length=100)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('avg_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_alert', models.PositiveIntegerField(default=100)),
                ('max_stock_alert', models.PositiveIntegerField(default=1000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pin Coil Summaries',
                'unique_together': {('coil_type',)},
            },
        ),
        migrations.CreateModel(
            name='StrappingRollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(max_length=100)),
                ('meters_per_roll', models.PositiveIntegerField()),
                ('weight_per_roll', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rolls', models.PositiveIntegerField(default=0)),
                ('total_meters', models.PositiveIntegerField(default=0)),
                ('avg_price_per_roll', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_alert', models.PositiveIntegerField(default=10)),
                ('max_stock_alert', models.PositiveIntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Strapping Roll Summaries',
                'unique_together': {('roll_type', 'meters_per_roll')},
            },
        ),
        migrations.DeleteModel(
            name='InventorySummary',
        ),
    ]
